name: Build, Push, and Test Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-test:
    runs-on: ubuntu-latest

    steps:
      #  Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      #  Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #  Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: amara864
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #  Build & push BACKEND image
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./src/tiny-bert-imdb/backend
          file: ./src/tiny-bert-imdb/backend/Dockerfile
          push: true
          tags: amara864/bert-tiny-imdb-backend:latest

      #  Build & push FRONTEND image
      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./src/tiny-bert-imdb/frontend
          file: ./src/tiny-bert-imdb/frontend/Dockerfile
          push: true
          tags: amara864/bert-tiny-imdb-frontend:latest

      #  Run Backend Container Test
      - name: Run backend container
        run: |
          docker run -d -p 8000:8000 --name imdb-backend amara864/bert-tiny-imdb-backend:latest
          echo "⏳ Waiting for backend to start..."
          sleep 10
          echo "Checking if container is running"
          docker ps
          echo " Container logs:"
          docker logs imdb-backend
          echo " Checking health endpoint (if FastAPI or similar)"
          curl --fail http://localhost:8000 || echo "⚠️ Could not reach backend"

      # 🧹 Clean up
      - name: Stop and remove container
        if: always()
        run: |
          docker stop imdb-backend || true
          docker rm imdb-backend || true
