name: Build, Push, and Run IMDb Containers

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-push-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (for advanced builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Backend image
      - name: Build Backend Image
        run: |
          docker build -t amara864/imdb-backend:latest -f src/backend.Dockerfile src

      # Step 5: Build Frontend image
      - name: Build Frontend Image
        run: |
          docker build -t amara864/imdb-frontend:latest -f src/frontend.Dockerfile src

      # Step 6: Push both images to Docker Hub
      - name: Push Docker Images
        run: |
          docker push amara864/imdb-backend:latest
          docker push amara864/imdb-frontend:latest

      # Step 7: Run Backend container
      - name: Run Backend Container
        run: |
          docker run -d --name imdb-backend -p 8000:8000 amara864/imdb-backend:latest
          sleep 10  # wait for backend to start

      # Step 8: Run Frontend container
      - name: Run Frontend Container
        run: |
          docker run -d --name imdb-frontend --link imdb-backend -p 8501:8501 amara864/imdb-frontend:latest

      # Step 9: Check running containers
      - name: Verify Running Containers
        run: docker ps -a

