name: Build, Push, and Run IMDb App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: amara864
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Verify repo structure
        run: |
          echo "Repo contents:"
          ls -R

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./bert-tiny-imdb
          file: bert-tiny-imdb/backend.Dockerfile
          push: true
          tags: amara864/imdb-backend:latest
          platforms: linux/amd64

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./bert-tiny-imdb
          file: bert-tiny-imdb/frontend.Dockerfile
          push: true
          tags: amara864/imdb-frontend:latest
          platforms: linux/amd64

      - name: Run Backend Container
        run: docker run -d --name imdb-backend -p 8000:8000 amara864/imdb-backend:latest

      - name: Run Frontend Container
        run: docker run -d --name imdb-frontend -p 8501:8501 amara864/imdb-frontend:latest

      - name: Check Running Containers
        run: docker ps -a
