 name: Check Repo Structure

on:
  workflow_dispatch:

jobs:
  check-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List everything
        run: |
          echo "=== Repo structure ==="
          ls -R
