name: Build Docker Image

on: # when to trigger the work flow
  push: # when code is pushed to branch
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: log into docker hub
        run: echo "${{secrets.DOCKER_PASSWORD}}"| docker login -u "${{secrets.DOCKER_USERNAME}}"

      
      - name: Build the image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/tiny-bert-imdb-model:latest . #amara864/tiny-bert-imdb-model:latest
        
        
      - name: Push Docker image om Docker hub
        run: docker push${{secrets.DOCKER_USERNAME}}/tiny-bert-imdb-model:latest
  