name: Build and Push BERT-TINY-IMDB Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Train model
        run: |
          cd src
          python train.py

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: amara864
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Backend Docker image
        run: |
          cd src
          docker build -t amara864/bert-tiny-imdb-backend:latest -f backend.Dockerfile .

      - name: Build Frontend Docker image
        run: |
          cd src
          docker build -t amara864/bert-tiny-imdb-frontend:latest -f frontend.Dockerfile .

      - name: Push Backend image to Docker Hub
        run: docker push amara864/bert-tiny-imdb-backend:latest

      - name: Push Frontend image to Docker Hub
        run: docker push amara864/bert-tiny-imdb-frontend:latest

      - name: Verify pushed images
        run: docker images | grep amara864
