name: Run IMDb Docker Container

on:
  workflow_dispatch:  # lets you manually run it from GitHub Actions tab
  push:
    branches:
      - main  # optional — run automatically on every push to main

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull the IMDb image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/tiny-bert-imdb-model:latest

      - name: Run the container
        run: docker run -d -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/tiny-bert-imdb-model:latest

      - name: Check running containers
        run: docker ps -a

